baseURL: "https://bennesp.github.io/"
title: bennesp
paginatation:
  pagerSize: 5
theme: papermod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-R4Z9PXP153

sitemap:

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.

  description: "Bennesp personal site"
  keywords: [bennesp, bennes, blog, devops, cloud, software]
  author: Me
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2 January 2006"
  defaultTheme: dark # auto, dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  ShowToc: true
  TocOpen: true

  assets:
    disableHLJS: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon/favicon-16x16.png"
    favicon32x32: "/favicon/favicon-32x32.png"
    apple_touch_icon: "/favicon/apple-touch-icon.png"
    safari_pinned_tab: "/favicon/apple-touch-icon.png"

  label:
    text: "bennesp"
    icon: /imgs/bennesp.png
    iconHeight: 32

  hideFooter: true

  # home-info mode
  homeInfoParams:
    Title: "Learning stuff 👨🏼‍💻"
    Content: I can't remember things, so I write them down here

  socialIcons:
    - name: github
      url: "https://github.com/bennesp"
    - name: bluesky
      url: "https://bsky.app/profile/bennes.bsky.social"
    - name: mastodon
      url: "https://k8s.social/@bennes"
    - name: linkedin
      url: "https://www.linkedin.com/in/benedetto-nespoli/"

  analytics:
    google:
      SiteVerificationTag: "v7Xf_l3PpxLV6QMfXaclOrUym7CgrmzJEBFXrAzWnZ4"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: true # hide on single page
    responsiveImages: true
    linkFullImages: false

  editPost:
    URL: "https://github.com/bennesp/bennesp.github.io/blob/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # For search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: search
      name: search
      url: /search/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    # Other cool themes: solarized-dark, github-dark, nord.
    # See https://xyproto.github.io/splash/docs/all.html
    style: catppuccin-mocha
    tabWidth: 2

outputs:
  home:
    - HTML
    - RSS
    - JSON # needed by search
